name: CI

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup spack
      uses: spack/setup-spack@v2.1.1
      with:
        ref: develop

    - name: Create spack environment
      run: |
        spack env create ci-env .github/spack.yaml

    - name: Add mochi-spack-packages
      run: |
        git clone https://github.com/mochi-hpc/mochi-spack-packages
        spack -e ci-env repo add mochi-spack-packages

    - name: Add requested package to spack environment
      run: |
        spack -e ci-env add ${{ inputs.package }}

    - name: Install spack environment
      run: |
        spack -e ci-env install

    - name: Show spack-installed packages for debugging
      run: |
        spack -e ci-env find -dlv

    - name: Push packages to buildcache and update index
      if: ${{ !cancelled() }}
      run: |
        spack -e ci-env mirror set --push \
        --oci-username ${{ github.actor }} \
        --oci-password "${{ secrets.GITHUB_TOKEN }}" mochi-buildcache
        spack -e ci-env buildcache push --base-image ubuntu:22.04 \
        --unsigned --update-index mochi-buildcache
